name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 35fdd575-2627-4b9d-aeb9-bf74a73116a5
          heroku_app_name: anotherdwbot3
          heroku_email: wuzzumva5l@zod.edu.pl
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_OWNER_ID: ${{secrets.OWNER_ID || '1881720028'}}
          HD_TELEGRAM_API: ${{secrets.TELEGRAM_API || '5310709'}}
          HD_TELEGRAM_HASH: ${{secrets.TELEGRAM_HASH || '63a546bdaf18e2cbba99f87b4274fa05'}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL || 'mongodb+srv://abcd:abcd@personalproject.mxx6dgi.mongodb.net/?retryWrites=true&w=majority'}}
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN || '5138249248:AAHUmRS5kBp5HlT399dtVrukHnmrdx2kfoY'}}
          
